# Generated by Django 3.1 on 2020-08-31 13:10

import books.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=30, verbose_name='도서명')),
                ('author', models.CharField(blank=True, max_length=30, verbose_name='저자')),
                ('publisher', models.CharField(blank=True, max_length=30, verbose_name='출판사')),
                ('intro', models.TextField(max_length=100, verbose_name='서평')),
                ('status', models.CharField(choices=[('대여가능', '대여 가능'), ('예약', '예약 중'), ('대여중', '대여 중'), ('대여불가능', '대여 불가능')], default='대여가능', max_length=10, verbose_name='상태')),
                ('bookcover', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=books.models.file_path)),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-stored_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.book')),
                ('comment', models.TextField(max_length=100, verbose_name='리뷰')),
                ('rate', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
            ],
        ),
    ]
